apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
      name: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: owncloud
        - name: MYSQL_USER
          value: owncloud
        - name: MYSQL_PASSWORD
          value: owncloud
        - name: MYSQL_DATABASE
          value: owncloud
        image: docker.io/mariadb:10.4
        imagePullPolicy: Always
        name: mariadb
        ports:
        - containerPort: 3306
          name: mariadb
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      - args:
        - 'trap : TERM INT; sleep infinity & wait'
        command:
        - /bin/bash
        - -c
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: owncloud
        image: docker.io/healthcheck/mysql:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/docker-healthcheck
          failureThreshold: 30
          initialDelaySeconds: 60
          timeoutSeconds: 3
        name: healthcheck
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/docker-healthcheck
          failureThreshold: 30
          initialDelaySeconds: 60
          timeoutSeconds: 3
      hostname: mariadb
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mariadb